"""01_initial-db

Revision ID: b9e90dab304f
Revises: 
Create Date: 2025-04-21 17:10:19.879901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9e90dab304f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'test_users',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('name', sa.String(50), nullable=False)
    )
    # op.add_column(
    #  'users',
    #  sa.Column('password_hash',
    #  sa.String(length=128))
    #  )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_users')
    # op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
